```mermaid

@startuml
(*) --> "Пользователь нажимает кнопку передвижения"
if "Там есть стена?" then
  -->[да] "Персонаж стоит на месте"
else
  -->[нет] "Персонаж передвигается на одну клетку"
(*) --> "Пользователь нажимает кнопку передвижения"
if "Там есть враг?" then
  -->[да] "Нанести ему урон"
else
  -->[нет] "Персонаж передвигается на одну клетку"
endif
endif
@enduml
