@startuml
[*] --> Начальное_состояние

state Начальное_состояние {
    [*] --> Пользователь_нажимает_кнопку_передвижения
    Пользователь_нажимает_кнопку_передвижения --> Проверка_наличия_стены : "Нажатие кнопки"
}

state Проверка_наличия_стены {
    Проверка_наличия_стены --> Персонаж_стоит_на_месте : "Там есть стена?"
    Проверка_наличия_стены --> Персонаж_передвигается_на_одну_клетку : "Там нет стены"
}

state Персонаж_стоит_на_месте {
    Персонаж_стоит_на_месте --> Пользователь_нажимает_кнопку_передвижения : "Нажатие кнопки"
}

state Персонаж_передвигается_на_одну_клетку {
    Персонаж_передвигается_на_одну_клетку --> Пользователь_нажимает_кнопку_передвижения : "Нажатие кнопки"
}
@enduml
