@startuml
(*) --> "Пользователь нажимает кнопку установки подбора предмета"
if "Под песонажем есть предмет?" then
  -->[нет] "Написать в чат об отсутсвии чего-либо"
else
  -->[да] "Убрать предмет с карты"
  --> "Положить предмет в инвентарь пользователю"
  --> (*)
  endif
@enduml
