@startuml
(*) --> "Пользователь нажимает кнопку передвижения"
if "Пользователь видел врагов?" then
  -->[да] "Враг делает шаг навстречу"
else
  -->[нет] "Враги стоят"
(*) --> "Пользователь нажимает кнопку передвижения"
if "Рядом с ним есть враг?" then
  -->[да] "Враг атакует пользователя"
else
  -->[нет] "Враг делает шаг навстречу"
--> (*)
endif
endif
@enduml
